export const REQUEST_HOLIDAY_SUCCESS = "REQUEST_HOLIDAY_SUCCESS",
  REQUEST_HOLIDAY_FAILED = "REQUEST_HOLIDAY_FAILED";

export const LOAD_EVENTS_SUCCESS = "LOAD_EVENTS_SUCCESS",
  LOAD_EVENTS_FAILED = "LOAD_EVENTS_FAILED",
  CANCEL_EVENT = "CANCEL_EVENT";

export const AUTH_INIT = "AUTH_INIT",
  AUTH_SUCCESS = "AUTH_SUCCESS",
  AUTH_FAILED = "AUTH_FAILED",
  AUTH_LOGOUT = "AUTH_LOGOUT";
