export const REQUEST_HOLIDAY_SUCCESS = "REQUEST_HOLIDAY_SUCCESS";
export const REQUEST_HOLIDAY_FAILED = "REQUEST_HOLIDAY_FAILED";


export const LOAD_EVENTS_SUCCESS = "LOAD_EVENTS_SUCCESS";
export const LOAD_EVENTS_FAILED = "LOAD_EVENTS_FAILED";
export const CANCEL_EVENT = "CANCEL_EVENT";
